#URL

url=https//a3h-staging-ap1.organization.com/

#Login

email_field=.//*[@id='user_email']
password_field=.//*[@id='user_password']
signin_button=.//*[@id='new_user']/table/tbody/tr[4]/td/input

#Overview

Map_view=.//*[@id='submenu']/a[1]
Custom_view=.//*[@id='submenu']/a[2]

# Report

Report=.//*[@id='nav_tabs']/ul/li[2]/a
Any_device=.//*[@id='tanks']/tbody/tr[2]/td[1]/a
Daily_summ=.//*[@id='submenu']/a[2]
Fill_events=.//*[@id='submenu']/a[3]
Gps_events=.//*[@id='submenu']/a[4]
Grap_summ=.//*[@id='submenu']/a[5]
#gps_events
Add_link=.//*[@id='row8315823']/td[3]/span
Close_popup=.//*[@id='map']/div/div[1]/div[4]/div[4]/div/div[3]
Delete_event=.//*[@id='row8315771']/td[6]/a/i
Export=.//*[@id='content']/div/table/tbody/tr/td[2]/a/i

#Tank Mgmt

Tank_Mgmt=.//*[@id='nav_tabs']/ul/li[6]/a
Statistics=.//*[@id='submenu']/a[1]
Del_exceptions=.//*[@id='submenu']/a[2]

#Routes

Routes=.//*[@id='nav_tabs']/ul/li[9]/a

#Groups

Groups=.//*[@id='nav_tabs']/ul/li[8]/a

#Users

Users=.//*[@id='nav_tabs']/ul/li[7]/a

#Settings

Settings=.//*[@id='nav_tabs']/ul/li[4]/a
Overview_cust=.//*[@id='submenu']/a
Left_arrow_mrk=.//*[@id='select-all-fields']
Right_arrow_mrk=.//*[@id='deselect-all-fields']

#Contact

Contact=.//*[@id='nav_tabs']/ul/li[3]/a

#ADMIN

Admin=.//*[@id='ub-login']/a[1]

#Overview

Overview=.//*[@id='nav_tabs']/ul/li[1]/a
Reads_sim=.//*[@id='content']/ul/li[9]/a

#Maintainence

Maintainence=.//*[@id='nav_tabs']/ul/li[2]/a

#Distributors

Distributors=.//*[@id='nav_tabs']/ul/li[3]/a
new=.//*[@id='subnav']/a
Name_field=.//*[@id='distributor_name']
Create_Dis=.//*[@id='new_distributor']/table/tbody/tr[8]/td/input
Next=//div[@class='fg-button ui-button ui-state-default next_page ']
Edit=.//*[@id='dists']/tbody/tr[2]/td[1]/a/i
Update_Dis=//input[@type="submit"]
Subdomain=.//*[@id='distributor_subdomain']
Cancel=.//*[@id='new_distributor']/table/tbody/tr[8]/td/a
Back=.//*[@id='subnav']/a
Dis_Delete=.//*[@id='dists']/tbody/tr[2]/td[8]/a/i
Imp_Met=.//*[@id='distributor_is_metric_distributor']

#Owners

Owners=.//*[@id='nav_tabs']/ul/li[4]/a
new=.//*[@id='subnav']/a

#Users

Users=.//*[@id='nav_tabs']/ul/li[5]/a
Users_dis=.//*[@id='nav_tabs']/ul/li[4]/a
Search_by_name=.//*[@id='search_first_name_or_last_name_cont']
Search_buttn=.//*[@id='content']/form/div[2]/div[1]/input[3]
Edit_user=.//*[@id='users']/tbody/tr/td[1]/a/i
Access_level=.//*[@id='user_access_level']
Update_user=//input[@type="submit"]

#Locations

Locations=.//*[@id='nav_tabs']/ul/li[6]/a

#Products

Products=.//*[@id='nav_tabs']/ul/li[7]/a
new=.//*[@id='subnav']/a

#Devices

Devices=.//*[@id='nav_tabs']/ul/li[8]/a

#Tanks

Tanks=.//*[@id='nav_tabs']/ul/li[9]/a
Tanks_dis=.//*[@id='nav_tabs']/ul/li[8]/a
Tanks_cus=.//*[@id='nav_tabs']/ul/li[5]/a
Filterbyowner=.//*[@id='search_device_account_id_eq']
Tanks_edit=.//*[@id='tanks']/tbody/tr[2]/td[2]/a/i
Edit_tank_profile=.//*[@id='show_tank_profile_form_button']
Tank_Geo=.//*[@id='tank_profile_tank_geometry_id']
Diameter=.//*[@id='tank_profile_geometry_v1']
Length=.//*[@id='tank_profile_geometry_v2']
Cal_cap_val=.//*[@id='calculate-capacity-and-values-button-js']
Set_tank_profile=.//*[@id='edit_tank_profile_partial']/table/tbody/tr[6]/td[2]/input
save_tank=.//*[@id='tank_form_submit']

#Tank Calibration

Tank_Cal=.//*[@id='nav_tabs']/ul/li[10]/a

#Tank Profiles

Tank_Pro=.//*[@id='nav_tabs']/ul/li[11]/a
Capacity=.//*[@id='tank_profile_capacity']
Strap_ch_val=.//*[@id='tank_profile_csv_values']
Create_tank_pro=.//*[@id='tank_profile_form_id']/table/tbody/tr[5]/td[2]/input
Tp_delete=.//*[@id='tank_profiles']/tbody/tr[4]/td[8]/a/i

#Data Feeds

Data_Feeds=.//*[@id='nav_tabs']/ul/li[12]/a

#DTM

DTM=.//*[@id='nav_tabs']/ul/li[13]/a
Commands=.//*[@id='subnav']/a

#Log_out

Log_out=.//*[@id='ub-login']/a[2]